### ISSUE TITLE
Wrong liquidity check on a token with 8 decimals

### ISSUE THREAD

**Issue by jondoeog** [CryptoGnome/LimitSwap#96]
Im, trading FIRE Protocol, it has 8 decimals (0xf921ae2dac5fa128dc0f6168bf153ea0943d2d43)

Pooled liquidity on /ETH pair is 300, the limitswap bot displays very low amount
![image](https://user-images.githubusercontent.com/74243437/103218117-7a9cb600-491a-11eb-8928-63748ac98870.png)

**Comment by CryptoGnome** [comment]
fixed

**Comment by jondoeog** [comment]
It's still wrong on newest version. As you can see on screen below, it seems to be using liquidity from first token in the list. Fire has different liquidity while bot think it's exactly the same as for 1st token (Glitch)

![image](https://user-images.githubusercontent.com/74243437/104885989-40e32c00-5969-11eb-9998-3c7ecda4af11.png)

**Comment by jondoeog** [comment]
It's still broken and not checking correctly the liquidity for other than 18 decimals tokens. I checked on Fire protocol and it displays huge liquidity while in reality it is 200 eth.
